### ISSUE TITLE
I can help for FR translations and MP Dedi-server testing

### ISSUE THREAD

**Issue by Lactic68** [ParamITNL/fs22-AnimalHelperMod#4]
Hi,
Thank you for your mod. 

If needed, I can help you with : 
- FR Translations
- MP dedi-server testing (I owned my self one)

**Comment by ParamITNL** [comment]
Hi Lactic68,

Thank you for offering your help!

- French translations are (very) welcome. 
- I think multiplayer won't work at the moment. I never tried and, to be honest, is not very high on my priority list to fix that, since I only play "singleplayer" myself.  As mentioned in the Readme, pull-requests for multiplayer support are welcome.

**Comment by ParamITNL** [comment]
Thanks for the pull-request!

**Comment by ParamITNL** [comment]
I created a new, separate issue for multiplayer support and will close this issue, since french translations are merged. Thanks for your contribution @Lactic68
